[ubuntu]
image=ubuntu:24.04
name="ubuntu-ros"
hostname="ubuntu-ros"
additional_packages="git vim tmux btop gcc g++ make cmake neofetch"
# Below is for ROS #
# jq as an alternative for the awk/sed stuff used in the official documentation #
additional_packages="software-properties-common curl jq libudev1 libudev-dev libboost-all-dev" 
init_hooks=export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | jq -r .tag_name)
init_hooks=curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/1.1.0/ros2-apt-source_1.1.0.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
init_hooks="dpkg -i /tmp/ros2-apt-source.deb"
init_hooks="apt update && apt install ros-dev-tools -y"
init_hooks="apt install ros-jazzy-ros-base -y"
