[ubuntu]
image=ubuntu:24.04
name="ubuntu-ros"
hostname="ubuntu-ros"
additional_packages="git vim tmux btop gcc g++ make cmake ffmpeg neofetch"

# Prepare to install VS Code #

additional_packages="wget gpg apt-transport-https"

# This structuring is odd. See the explanation below (in the ROS section) #
init_hooks=if [ ! -f /usr/bin/code ]; then echo "Install VS Code"
init_hooks=echo "code code/add-microsoft-repo boolean true" | debconf-set-selections
init_hooks="wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg"
init_hooks="install -D -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft.gpg"
init_hooks="rm -f microsoft.gpg"
init_hooks="touch /etc/apt/sources.list.d/vscode.sources"
init_hooks=echo "Types: deb" >> /etc/apt/sources.list.d/vscode.sources
init_hooks=echo "URIs: https://packages.microsoft.com/repos/code" >> /etc/apt/sources.list.d/vscode.sources
init_hooks=echo "Suites: stable" >> /etc/apt/sources.list.d/vscode.sources
init_hooks=echo "Components: main" >> /etc/apt/sources.list.d/vscode.sources
init_hooks=echo "Architectures: amd64,arm64,armhf" >> /etc/apt/sources.list.d/vscode.sources
init_hooks=echo "Signed-By: /usr/share/keyrings/microsoft.gpg" >> /etc/apt/sources.list.d/vscode.sources
init_hooks="apt update && apt install code -y; fi"

# Install ROS2 Jazzy #

# jq as an alternative for the awk/sed stuff used in the official documentation #
additional_packages="software-properties-common curl jq libudev1 libudev-dev libboost-all-dev" 

# This odd structuring means that we only try to install ROS if it's not already installed. #
# distrobox concatenates init_hooks together by placing "&&" between them. We exploit that to avoid #
# having to write everything on one line. Including the echo command on the first line allows the #
# syntax to work out: 'if [ ! -d /opt/ros/jazzy ]; then echo "Install ROS" && export ... && apt #
# install ros-jazzy-ros-base -y; fi' is valid syntax, but 'if [ ! -d /opt/ros/jazzy ]; then && #
# export ...' is not.
init_hooks=if [ ! -d /opt/ros/jazzy ]; then echo "Install ROS"
init_hooks=export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | jq -r .tag_name)
init_hooks=curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/1.1.0/ros2-apt-source_1.1.0.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
init_hooks="dpkg -i /tmp/ros2-apt-source.deb"
init_hooks="apt update && apt install ros-dev-tools -y"
init_hooks="apt install ros-jazzy-ros-base ros-jazzy-rosbridge-server -y; fi"
